name: PR target

on:
    pull_request_target:
        types: [synchronize, opened]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
    group: ci-tests-${{ github.ref }}-PRT
    cancel-in-progress: true

jobs:
    debs-cache:
        runs-on: ubuntu-latest
        steps:
            - name: Debs-Cache
              uses: ./.github/actions/debs-cache/

    check-locale:
        needs: [debs-cache]
        runs-on: ubuntu-latest
        steps:
            - name: Check locale
              uses: ./.github/actions/check-locale/

    size-report:
        needs: [debs-cache]
        runs-on: ubuntu-latest
        steps:
            - name: Size report
              uses: ./.github/actions/size-report/
